const Map<String, String> ar = {
  "Arabic":"اللغة العربية",
  "Sign Up":"تسجيل حساب جديد",
  "English":"اللغة الإنجليزية",
  "Done !":"حسنا",
  "Doctors":"أطباء",
  'Have you faced any problem?':"هل واجهتك أي مشكلة؟",
  'National Id':"الرقم القومي",
  "Please check your email, password reset link has been sent to you.": "يرجى التحقق من بريدك الإلكتروني ، تم إرسال رابط إعادة تعيين كلمة المرور إليك.",
  "Continue": "اكمل",
  "Oops, Failed!": "عفوًا ، فشل!",
  "Try Again": "حاول مجددا",
  "Cancel":"الغاء",
  "Forgot Password": "هل نسيت كلمة السر",
  "Enter your email to verify that its you !":
  "أدخل بريدك الإلكتروني للتحقق من أنه أنت!",
  "this field is required ! ": "هذه الخانة مطلوبه !",
  "Email": "الايميل",
  "Verify":"يؤكد",
  "User Not Found ! ":"لم يتم العثور على المستخدم !",
  'No user found for that email.':"لم يتم العثور على مستخدم لهذا البريد الإلكتروني.",
  "you entered wrong password!":"أدخلت كلمة مرور خاطئة!",
  "'Wrong password provided for that user.'":"تم توفير كلمة مرور خاطئة لهذا المستخدم",
  "Not Valid":"غير صالح",
  "Login To Your Account":"تسجيل الدخول إلى حسابك",
  "Password":"كلمة المرور",
  "Remember me":"تذكرني",
  "Sign In":"تسجيل الدخول",
  "Forgot The Password?":"هل نسيت كلمة المرور؟",
  "or Continue with":"أو متابعة",
  "Don’t have an account ?":"ليس لديك حساب؟",
  "SignUp":"إنشاء حساب جديد",
  'Login cancelled':"تم إلغاء تسجيل الدخول",
  'Error':"خطأ",
  "Your Password is very weak ! ":"كلمة المرور الخاصة بك ضعيفة للغاية!",
  'the password is too weak.':"كلمه المرور ضعيفه للغايه.",
  "This email is already in use ! ":"هذا البريد استخدم من قبل !",
  'the email already exists for the email.':"البريد الإلكتروني موجود بالفعل للبريد الإلكتروني.",
  "Create New Account":"انشاء حساب جديد",
  "OR Sign Up With":"او قم بتسجيل الدخول باستخدام",
  "Already have an account ?":"هل لديك حساب؟",
  "Get Started":"البدء",
  "A medical application for healthy liver to help both the doctor and the patient":"تطبيق طبي لكبد سليم لمساعدة كل من الطبيب والمريض",
  "Next":"التالي",
  """
Thousands of """:"آلاف من",
  """
doctors & experts to """:"أطباء وخبراء لـ ",
  """
help your health!""":"مساعدة صحتك! ",
  "Health Checks":"فحوصات طبية",
  "and consultation":"والتشاور",
  "anywhere anytime":"في أي مكان وفي أي وقت",
  "Lets start living":"لنبدأ العيش",
  "healthy and well ":"بصحة جيدة",
  "with us right now":"معنا الآن",
  'Welcome to':'مرحبا بك في',
  'Hepatica!':"هيباتيكا!",
  'Add your review':'إضافة تقييمك',
  'How was your experience with Dr. Mostafa ali?':"كيف كانت تجربتك مع الدكتور مصطفى علي؟",
  'Write your review':'اكتب مراجعتك',
  'write your review here':"اكتب رأيك هنا",
  'Would recommend Dr. Mostafa ali to  your friends?':"هل تنصح أصدقاءك بالدكتور مصطفى علي؟",
  'Yes':"نعم",
  'No':"لا",
  "review successfully":"تمت المراجعة بنجاح",
  "Your review has been":"لقد كان تعليقك",
  "successfully submitted":"قدمت بنجاح",
  "thank you very much":"شكراً جزيلاً",
  'Submit':'إرسال',
  'How was your experience with El_Shefaa Lab?':"كيف كانت تجربتك مع معمل الشفاء؟",
  'Would recommend El Shafaa Lab to  your friends?':"هل تنصح أصدقاءك بمعمل الشفاء؟",
  'Review Successful':"المراجعة ناجحة",
  'Your review has been successfully submitted thank you very much ':"تم إرسال تعليقك بنجاح ، شكرًا جزيلاً لك",
  'OK':"تم",
  'Rate the app':'قيم التطبيق',
  'Was the app easy for you?':"هل كان التطبيق سهلاً بالنسبة لك؟",
  'Was dealing through the application convenient for you?':"هل كان التعامل من خلال التطبيق مناسبًا لك؟",
  'Have you faced any problemed?':"هل واجهت أي مشكلة؟",
  'Do you have any suggestions for making the app better?':"هل لديك أي اقتراحات لتحسين التطبيق؟",
  'Rate':'معدل',
  "Dr.Mostafa Ali":"دكتور مصطفى علي",
  "Professor and Head of Gastroenterology Department at Al-AMAL specialised Hospital ":"أستاذ ورئيس قسم أمراض الجهاز الهضمي بمستشفى الأمل التخصصي",
  'Login': "تسجيل دخول",
  "About me":"عني",
  "Dr.Mostafa Ali is a Professor and Head of Gastroenterology Department at Al-AMAL specialised Hospital .":". الدكتور مصطفى علي هو أستاذ ورئيس قسم أمراض الجهاز الهضمي في مستشفى الأمل التخصصي",
  "He has won many awards . Graduated with honors at the faulty of medicine": "لقد فاز بالعديد من الجوائز. تخرج مع مرتبة الشرف في خطأ الطب ",
  "Monday-Friday at 8AM-20PM": "من الاثنين إلى الجمعة من الساعة 8 صباحا حتى 20 مساء",
  "Reviewers": "المراجعون",
  "View All":"عرض الكل",
  "Dr:mostafa is very professional in his work my problems were solved thanks to him.": ".الدكتور مصطفى محترف جدا في عمله تم حل مشاكلي بفضله",
  "He is trusted doctor.":"إنه طبيب موثوق به.",
  "Book Appointment":"حجز موعد",
  'Hi, Nawal':'مرحبا نوال',
  'We are here for your':'نحن هنا من أجلك',
  'medicine':'الطب',
  ' daily reminder':' تذكير يومي',
  'search medications':'البحث عن الأدوية',
  'Daily dose':'الجرعة اليومية',
  'Today':'اليوم',
  'Omega Plus':'أوميغا بلس',
  'omega 3,once daily after meal':'أوميغا 3 ، مرة واحدة يوميا بعد الوجبة',
  '9:00 AM':'9:00 صباحا',
  'Vitamin D3':'فيتامين د3',
  'cholecalcalferol,twice daily ':' كوليكالكالفيرول ، مرتين يوميا',
  'Gynera':'جينيرا',
  'Gestodene 0.75mg,once daily ':' جيستودين 0.75 مجم ، مرة واحدة يوميا',
  '2:00 PM':'2:00 مساء',
  'Zyrtec':'زيرتيك',
  'cetrzin 30mg,1 pill before sleep':'Cetrzin 30mg ، 1 حبوب منع الحمل قبل النوم',
  '11:00 PM':'11:00 مساء',
  'Vitamin E':'فيتامين ه',
  'cholecalcalferol,twice daily':'كوليكالكالفيرول، مرتين يوميا',
  '11:00 AM':'11:00 صباحا',
  'Hi, DR Mostafa ':' مرحبا دكتور مصطفى',
  'Nawal`s ':' نوال',
  'Prescribed':'موصوف',
  "Fill Your Profile":"املأ ملفك الشخصي",
  'Name must not be empty':'يجب ألا يكون الاسم فارغا',
  'First Name':'الاسم الأول',
  'Last Name':'اسم العائلة',
  'ID must not be empty':'يجب ألا تكون بطاقة الهوية فارغة',
  'Address must not be empty':'يجب ألا يكون العنوان فارغا',
  'Address(city,street)':'العنوان (المدينة ، الشارع)',
  'Current Place Of Work must not be empty':'يجب ألا يكون مكان العمل الحالي فارغا',
  'Governorate':'المحافظة',
  'phone must not be empty':'يجب ألا يكون الهاتف فارغا',
  'phone Number':'رقم الهاتف',
  'Date Of Birth must not be empty':'يجب ألا يكون تاريخ الميلاد فارغا',
  'Date Of Birth':'تاريخ الميلاد',
  'years of experience must not be empty':'يجب ألا تكون سنوات الخبرة فارغة',
  'Years of experience':'سنوات من الخبرة',
  'qualification must not be empty':'يجب ألا يكون المؤهل فارغ',
  'Qualifications':'المؤهلات',
  "Male":"ذكر",
  "male":"ذكر",
  "Female":"أنثى",
  "female":"أنثى",

  "Recommended Doctors":"الأطباء الموصى بها",
  "DR.Hossam Ali":"د. حسام علي",
  "DR.Haidy Khalil":"د. هايدي خليل",
  "DR.Ali Mohamed":"د. علي محمد",
  "DR.Hana Ahmed":"د. هناء أحمد",
  "DR.Mariem Ibrahim": "د. مريم إبراهيم",
  "DR.Nawal Swaky":"د. نوال شوقي",
  "Professor and Head of Medicine in Gastroenterology  at Al-Amal hosiptal  ":  "أستاذ ورئيس قسم طب الجهاز الهضمي في مستشفى الأمل",
  'Add New Event':'إضافة حدث جديد',
  'Reschedule Appointment':'إعادة جدولة الموعد',
  'Select Date':'اختر التاريخ',
  'Event Title':'عنوان الحدث',
  'Description':'الوصف',
  '10:00 AM':'10:00 صباحا',
  '10:30 AM':'10:30 صباحا',
  '11:30 AM':'11:30 صباحا',
  '12:00 PM':'12:00 ظهرا',
  '12:30 PM':'12:30 PM',
  '1:00 PM':'1:00 مساء',
  'Add Event':'إضافة حدث',
  'There are no favorites yet!':'لا توجد مفضلات حتى الآن!',
  "Home":"الصفحه الرئيسيه",
  "Appointement":"موعد",
  "Reminder":"تذكير",
  "Chat":"الدردشة",
  "Profile":"الملف الشخصي",
  "Good Morning":"صباح الخير",
  "40%":"40%",
  "choose language :":"اختر اللغة :",
  "Greet offers on lab tests and sessions by code":" عروض على الاختبارات المعملية والجلسات حسب الكود",
  "3-year experience": "خبرة 3 سنوات",
  "2-year experience":"خبرة 2 سنة",
  "Dr.muhammad Omar":"د. محمد عمر",
  "Dr.Hossam Ahmed":"د.حسام أحمد",
  "Dr.Hana Ahmed":"د.هنا أحمد",
  "4-year experience": "خبرة 4 سنوات",
  "Recommended Labs":  "المختبرات الموصى بها",
  "Al-Hayah Lab":"مختبر الحياة",
  "Medical Analysis Lab":"مختبر التحاليل الطبية",
  "El-Shorouk Lab":"معمل الشروق",
  "Al-Mostakbal Lab":"مختبر المستقبل",
  "HLL Lab":"مختبر HLL",
  "El-Shoruq lab":"معمل الشروق",
  "El-Shefaa lab":  "مختبر الشفاء" ,
  "El-Sehah lab":"مختبر الصحاح",
  "El-Amal lab": "معمل الأمل" ,
  "Medical analysis lab and radiology center.": ".مختبر التحاليل الطبية ومركز الأشعة",
  "Current Labs":"المختبرات الحالية",
  ' Your Address':'عنوانك',
  'Your blood type must not be empty':'يجب الا تكون فصيلة الدم فارغ',
  ' Your blood type':'فصيلة الدم',
  'must not be empty':'يجب ألا تكون فارغة',
  ' Do you from Suffer from any allergies ?': 'هل تعاني من أي حساسية؟',
  ' Graduation year must not be empty':'يجب ألا تكون سنة التخرج فارغة',
  'allergies must not be empty':'يجب ألا تكون الحساسية فارغة',
  'Do you suffer any allergies':'هل تعاني من أي حساسية',
  "Mohamed Ibrahim":"محمد إبراهيم",
  "Nawal Swaky": "نوال شوقي",
  "Ali Selam":"علي سلام",
  "bola Samy":"بولا سامي",
  "C virus patient, He is 35 years old ,now in treatment phase.":   ".مريض بفيروس سي، يبلغ من العمر 35 عاما ، وهو الآن في مرحلة العلاج",
  "patient with cirrhosis, she is 40 old years, the treatment stage":  "مريضة مصابة بتليف الكبد ، تبلغ من العمر 40 عاما ،, وهو الآن في مرحلة العلاج",
  "A virus patient, He is 50 years old ,now in treatment phase.  ": ".مريض بالفيروس ا، يبلغ من العمر 50 عاما ، وهو الآن في مرحلة العلاج  ",
  "patient with cancer, she is 35 old years, the treatment stage ":  "مريضة مصابة بالسرطان ، تبلغ من العمر 35 عاما ،وهو الآن في مرحلة العلاج ",
  "B virus patient, He is 50 years old ,now in treatment phase.  ":".مريض بفيروس ب ، يبلغ من العمر 50 عاما ، وهو الآن في مرحلة العلاج  ",
  "patient with cancer, she is 40 old years, the treatment stage":"مريضة بالسرطان ، تبلغ من العمر 40 عاما ، وهو الآن في مرحلة العلاج",
  "Current Patients":"المرضى الحاليون",
  "Payments": "المدفوعات",
  "Select the payment method you want to use.":".حدد طريقة الدفع التي تريد استخدامها",
  "Paypal":"PayPal",
  "Google Pay":"Google Pay",
  "Apple Pay":"Apple Pay",
  "Payment":"الدفع",
  ".... .... .... 7285":".... .... .... 7285",
  "Edit Profile":"تغير الملف الشخصى",
  "Notification":"الإخطار",
  "Language":"اللغة",
  "Doctor Report":"تقرير الطبيب",
  "Medication":"الدواء",
  "Labs":"مختبرات",
  "Appointment":"موعد",
  "Logout":"تسجيل الخروج",
  'Special Offer':'عرض خاص',
  'A new offer is availabile, ': ' ,عرض جديد متاح',
  'This offer allows you to  sessions you can have the offer by entering the code you got from the doctor. ':' .يتيح لك هذا العرض جلسات يمكنك الحصول على العرض عن طريق إدخال الرمز الذي حصلت عليه من الطبيب',
  'Note : please,Allow notifications alerts so that you can know about our ':'ملاحظة: من فضلك ، السماح بتنبيهات الإشعارات حتى تتمكن من معرفة المزيد عن موقعنا ',
  'special offers and do not miss them.':'عروض خاصة ولا تفوتها',
  'Get The Offer':'احصل على العرض',
  'Confirm that you are a doctor':'تأكد من أنك طبيب',
  'Please Upload  Your Medical License': "يرجى تحميل رخصتك الطبية",
  'Note: please make sure that your medical license is as clear as possible.': ".ملاحظة: يرجى التأكد من أن رخصتك الطبية واضحة قدر الإمكان",
  "Choose Whether you are a :":"اختر ما إذا كنت ",
  "Doctor":"دكتور",
  "Patient":"مريض",
  "Dr:mostafa is very professional in his work my problems were solved thanks to him."
      "He is trusted doctor.":"د.مصطفي متقن لعمله .تم حل كل مشاكلي الصحيه .هو دكتور موثوق",
  "Working Time":"ساعات العمل",
"Dr.Mostafa Ali is a Professor and Head of Gastroenterology Department at Al-AMAL specialised Hospital ."
"He has won many awards . Graduated with honors at the faulty of medicine":"الدكتور مصطفى علي هو أستاذ ورئيس قسم أمراض الجهاز الهضمي في مستشفى الأمل التخصصي."
      "لقد فاز بالعديد من الجوائز. تخرج مع مرتبة الشرف في خطأ من الطب",
    'A medical application for healthy liver \n'
    'to help both the doctor and the patient': 'تطبيق طبي لصحة الكبد لمساعدة\n   كل من الطبيب والمريض'
};
